### ISSUE TITLE
Errors in configuration are silently ignored

### ISSUE THREAD

**Issue by hashworks** [Anomalocaridid/handlr-regex#82]
Errors in the `~/.config/handlr/handlr.toml` are silently ignored. In example, the following configuration has a bad regex (missing closing `]` after `s`):

```toml
enable_selector = true

[[handlers]]
exec = "/usr/lib/firefox/firefox -P someprofile %u"
regexes = ['^http[s?:\/\/(.*\.)?(example.net|example.com)([\/?#].*)?$']
```

Running `handlr get x-scheme-handler/https` will fail to parse it, ignoring it silently and falling back to default. One can test this with multiple handlers for `x-scheme-handler/https`, in this case `handlr` will fall back to its default `enable_selector` and won't ask for the application to use.

While I see that it's reasonable to fall back to the default to ensure basic app opening still works, `handlr` should at least send a message to stderr (and maybe exit with code 2), especially if used in a terminal.
